version: '3.8'

services:
  claude-daemon:
    build: .
    ports:
      - "5000:5000"
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/data/claude-daemon.db
      - LOG_LEVEL=debug
    volumes:
      - ./data:/data
      - ./logs:/app/logs
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "tools/health-check.js"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - claude-daemon
    restart: unless-stopped

volumes:
  redis_data: