version: '3.8'

services:
  claude-daemon:
    build: .
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - DATABASE_PATH=/data/claude-daemon.db
    volumes:
      - claude_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  claude_data: