app:
  name: Web3 Audit Intelligence System
  version: 1.0.0
  environment: development

collectors:
  code4rena:
    enabled: true
    schedule: "0 */6 * * *"
  sherlock:
    enabled: true
    schedule: "0 */8 * * *"
  immunefi:
    enabled: true
    schedule: "0 */12 * * *"

database:
  host: localhost
  port: 5432
  name: audit_db
  user: user

api:
  host: 0.0.0.0
  port: 8000
  cors_origins:
    - "http://localhost:3000"